//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicantManagementSystemDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicantFamilyDetail
    {
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string RelationWithApplicant { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public int Id { get; set; }
    
        public virtual ApplicantDetail ApplicantDetail { get; set; }
    }
}
